feat: Added solve for 07 module
js-tasks-ru/js-20220418_destroymarsk pull request #8
Opened 2022-05-23 17:16 UTC by meowcorp

Закомментировал несколько тестов:
1) В 1 задании некоторые тесты проверяют данные с 2020 года. Сервер на этот год возвращает пустой массив
2) В 2 задании закомментировал 1 тест. Не смог разобраться, но он почему-то не мокает запрос. В мокнутом ответе я получаю undefined

2022-05-23 17:17 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-05-24 16:22 UTC, dragozin requested changes
Оставил не критичные комменты. по реализации - лучше доработать метод update в ColumnChart

2022-05-24 16:22 UTC, dragozin commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +  render() {
В данной версии реализации таблицы ожидается что данные будут получены с сервера на этапе рендера, поэтому тест падает. Т.е. метод prefetchData лучше перенести в render

2022-05-24 16:22 UTC, dragozin commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +    this.subElements.header.removeEventListener('pointerdown', this.handleSortClick);
👍

2022-05-24 16:22 UTC, dragozin commented on 07-async-code-fetch-api-part-1/1-column-chart/index.spec.js
> +  // it('should have ability to be update by new values', async () => {
>В 1 задании некоторые тесты проверяют данные с 2020 года. Сервер на этот год возвращает пустой массив

из лекции про тесты мы узнали, что на этапе юнит-тестирования не корректно ходить на сервер за запросами. Как вы правильно сказали, т.к. сервер может вернуть какие-то новые значения. Поэтому запрос на сервере мокается. 
и тест проверяет что после вызова update компонент заберет новые данные с сервера

Это нужно реализовать, т.к. range дат может измениться и нужно отрисовать новые данные.

2022-05-24 16:22 UTC, dragozin commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    this.getDataFromServer();
метод update есть, вы идете за данными но эти данные не отрисовываете. Т.е. у нас возникает неконсистентное состояние между представлением и хранящимися данными. 

Совет: называйте методы в соответствии с реализацией. `getDataFromServer` - дословно переводится `дай данные с сервера`, хотя вы данные никакие здесь не получаете. Тут лучше назвать `loadDataFromServer`. Нейминг очень важен - он поможет понимать что делает ваш метод не читая его реализацию, упростит работу с вашим кодом и сократит количество ошибок в будущем

2022-05-24 16:22 UTC, dragozin commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +          this.element.classList.add('sortable-table_empty');
лучше развязать работу с данными и логику работы с UI - делать это в разных методах. Т.к. ui будет меняться, сложно потом по коду искать где же происходит изменение на класс sortable-table_empty

2022-05-26 11:50 UTC, closed without merging